### ISSUE TITLE
Identification of Attributes by name instead of type

### ISSUE THREAD

**Issue by mrdavidkovacs** [oliverhanappi/ManualMappingGuard#2]
# Problem
Attributes are identified by name instead of type.
Therefore, subclasses of attributes are not taken into account by the analyzer logic.

**Comment by oliverhanappi** [comment]
I am afraid that supporting subclasses of the attributes is not possible. The analyzer requires to determine the values of the constructor arguments at compile time, which may not always be possible when allowing subclasses of the attributes. The analyzer therefore expects certain well known constructor signatures.

Consider for instance the following (rather senseless) derived attribute. It determines at runtime, thus not at compile time, which property should be ignored.

```csharp
public class CustomUnmappedPropertyAttribute : UnmappedPropertyAttribute
{
    public CustomUnmappedPropertyAttribute()
        : base("Property" + new Random().Next(1, 10))
    {
    }
}
```

It would currently be possible to allow subclasses of `MappingMethodAttribute` and `MappingTargetAttribute`, because both of them have no constructor arguments, however that may change in future.

I think it would be best to seal the attributes to avoid people from deriving them by mistake.

What do you think? Am I missing here something? Do you have another suggestion?

**Comment by mrdavidkovacs** [comment]
I've got an working example for my issue. See #3 

If this is not intended it would be great to make the attributes sealed to show the developers that inheritance is not supported.

**Comment by oliverhanappi** [comment]
Thanks for the pull request, however it will only work for szenarios in which the original constructor signature is not changed. See my comment within the pull request.

**Comment by mrdavidkovacs** [comment]
Which wouldn't be so bad in my opinion, as one can do the following:
```cs
  [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
  public class BaseTypeUnmappedPropertiesAttribute : UnmappedPropertiesAttribute
  {
    public BaseTypeUnmappedPropertiesAttribute() 
      : base(GetUnmappedPropertyNames())
    {
    }

    private static string[] GetUnmappedPropertyNames()
    {
      return new[]
      {
        nameof(BaseType.PropertyA),
        nameof(BaseType.PropertyB),
      };
    }
  }
```

What is your opinion?

**Comment by oliverhanappi** [comment]
How do you extract the property names within the analyzer? Afaik this is not possible and your pull request does not solve this issue. Using such an attribute would imho result in an exception within the analyzer (not tested).

**Comment by mrdavidkovacs** [comment]
I got your point.
I have a solution for this problem but this includes dynamic compiling and executing, which goes a little bit too far.
So I cancelled the PR #3.

I will drop a new one to make the attribute classes sealed.

**Comment by oliverhanappi** [comment]
Thanks for your pull request #4. [Version 1.1.1](https://www.nuget.org/packages/ManualMappingGuard/1.1.1) is out now.
